import "./globals.css";
import Footer from "@/components/Footer/Footer";
import Nav from "@/components/Navbar/Nav";
import Navbar from "@/components/Navbar/Navbar";
export const metadata = {
  title: "Dashboard | E-Stack Bond",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <Navbar /> */}
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
